Repository anoma/vamp-ir, pull requests merged in 2023-06, with the labels that each got.

#102 Clippy and FMT code improvements.
  src/ast.rs
  src/error.rs
  src/halo2/cli.rs
  src/halo2/synth.rs
  src/lib.rs
  src/main.rs
  src/plonk/synth.rs
  src/transform.rs
  src/typecheck.rs
  src/util.rs
Labels: enhancement

#104 Add json5 support for witness inputs
  Cargo.toml
  src/util.rs
Labels: enhancement

#112 Closes #111
  .github/workflows/release.yml
  .github/workflows/test-build.yml
Labels: enhancement, CI

#101 Implement REPL
  benches/plonk_benches.rs
  src/error.rs
  src/lib.rs
  src/main.rs
  src/repl/cli.rs
  src/repl/mod.rs
  src/transform.rs
Labels: enhancement, repl, CLI
